// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_base/test/data/repository/remote/app_api_helper_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:flutter_base/data/app_error.dart' as _i8;
import 'package:flutter_base/data/model/movie.dart' as _i7;
import 'package:flutter_base/data/model/result.dart' as _i3;
import 'package:flutter_base/data/model/season.dart' as _i6;
import 'package:flutter_base/data/repository/remote/api_service_end_point.dart'
    as _i2;
import 'package:flutter_base/data/repository/remote/app_api_helper.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeApiServiceEndPoint_0 extends _i1.Fake
    implements _i2.ApiServiceEndPoint {}

class _FakeApiServiceEndPointMovie_1 extends _i1.Fake
    implements _i2.ApiServiceEndPointMovie {}

class _FakeResult_2<T> extends _i1.Fake implements _i3.Result<T> {}

/// A class which mocks [AppApiHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppApiHelper extends _i1.Mock implements _i4.AppApiHelper {
  MockAppApiHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiServiceEndPoint get serviceEndPoint =>
      (super.noSuchMethod(Invocation.getter(#serviceEndPoint),
          returnValue: _FakeApiServiceEndPoint_0()) as _i2.ApiServiceEndPoint);
  @override
  _i2.ApiServiceEndPointMovie get serviceEndPointMovie =>
      (super.noSuchMethod(Invocation.getter(#serviceEndPointMovie),
              returnValue: _FakeApiServiceEndPointMovie_1())
          as _i2.ApiServiceEndPointMovie);
  @override
  _i5.Future<_i3.Result<_i6.Season>> getMangaSeason(
          String? playlistID, String? profileID) =>
      (super.noSuchMethod(
              Invocation.method(#getMangaSeason, [playlistID, profileID]),
              returnValue: Future<_i3.Result<_i6.Season>>.value(
                  _FakeResult_2<_i6.Season>()))
          as _i5.Future<_i3.Result<_i6.Season>>);
  @override
  _i5.Future<_i3.Result<_i7.Movie>> getMovie(String? slug, String? id) =>
      (super.noSuchMethod(Invocation.method(#getMovie, [slug, id]),
              returnValue: Future<_i3.Result<_i7.Movie>>.value(
                  _FakeResult_2<_i7.Movie>()))
          as _i5.Future<_i3.Result<_i7.Movie>>);
}

/// A class which mocks [AppError].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppError extends _i1.Mock implements _i8.AppError {
  MockAppError() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set message(String? _message) =>
      super.noSuchMethod(Invocation.setter(#message, _message),
          returnValueForMissingStub: null);
  @override
  set type(_i8.AppErrorType? _type) =>
      super.noSuchMethod(Invocation.setter(#type, _type),
          returnValueForMissingStub: null);
}
